export const maharashtraDistrictData = [
  { district: "Ahmednagar", expected_check_percent: 75, actual_check_percent: 52 },
  { district: "Akola", expected_check_percent: 70, actual_check_percent: 61 },
  { district: "Amravati", expected_check_percent: 72, actual_check_percent: 58 },
  { district: "Aurangabad", expected_check_percent: 78, actual_check_percent: 54 },
  { district: "Beed", expected_check_percent: 68, actual_check_percent: 43 },
  { district: "Bhandara", expected_check_percent: 65, actual_check_percent: 57 },
  { district: "Buldhana", expected_check_percent: 70, actual_check_percent: 49 },
  { district: "Chandrapur", expected_check_percent: 73, actual_check_percent: 60 },
  { district: "Dhule", expected_check_percent: 67, actual_check_percent: 44 },
  { district: "Gadchiroli", expected_check_percent: 60, actual_check_percent: 31 },
  { district: "Gondia", expected_check_percent: 66, actual_check_percent: 55 },
  { district: "Hingoli", expected_check_percent: 64, actual_check_percent: 40 },
  { district: "Jalgaon", expected_check_percent: 71, actual_check_percent: 56 },
  { district: "Jalna", expected_check_percent: 66, actual_check_percent: 42 },
  { district: "Kolhapur", expected_check_percent: 80, actual_check_percent: 69 },
  { district: "Latur", expected_check_percent: 69, actual_check_percent: 48 },
  { district: "Mumbai City", expected_check_percent: 88, actual_check_percent: 77 },
  { district: "Mumbai Suburban", expected_check_percent: 85, actual_check_percent: 72 },
  { district: "Nagpur", expected_check_percent: 82, actual_check_percent: 70 },
  { district: "Nanded", expected_check_percent: 68, actual_check_percent: 45 },
  { district: "Nandurbar", expected_check_percent: 62, actual_check_percent: 33 },
  { district: "Nashik", expected_check_percent: 76, actual_check_percent: 62 },
  { district: "Osmanabad", expected_check_percent: 65, actual_check_percent: 41 },
  { district: "Palghar", expected_check_percent: 70, actual_check_percent: 50 },
  { district: "Parbhani", expected_check_percent: 66, actual_check_percent: 44 },
  { district: "Pune", expected_check_percent: 85, actual_check_percent: 74 },
  { district: "Raigad", expected_check_percent: 74, actual_check_percent: 60 },
  { district: "Ratnagiri", expected_check_percent: 72, actual_check_percent: 58 },
  { district: "Sangli", expected_check_percent: 77, actual_check_percent: 64 },
  { district: "Satara", expected_check_percent: 76, actual_check_percent: 63 },
  { district: "Sindhudurg", expected_check_percent: 70, actual_check_percent: 59 },
  { district: "Solapur", expected_check_percent: 74, actual_check_percent: 55 },
  { district: "Thane", expected_check_percent: 83, actual_check_percent: 68 },
  { district: "Wardha", expected_check_percent: 68, actual_check_percent: 57 },
  { district: "Washim", expected_check_percent: 64, actual_check_percent: 46 },
  { district: "Yavatmal", expected_check_percent: 67, actual_check_percent: 48 },
];
