export const maharashtraDistrictData = [
  { district: "Ahmednagar", expected_check_percent: 75, actual_check_percent: 52 },
  { district: "Akola", expected_check_percent: 70, actual_check_percent: 61 },
  { district: "Amravati", expected_check_percent: 72, actual_check_percent: 58 },
  { district: "Aurangabad", expected_check_percent: 78, actual_check_percent: 54 },
  { district: "Beed", expected_check_percent: 68, actual_check_percent: 43 },
  { district: "Bhandara", expected_check_percent: 65, actual_check_percent: 57 },
  { district: "Buldhana", expected_check_percent: 70, actual_check_percent: 49 },
  { district: "Chandrapur", expected_check_percent: 73, actual_check_percent: 60 },
  { district: "Dhule", expected_check_percent: 67, actual_check_percent: 44 },
  { district: "Gadchiroli", expected_check_percent: 60, actual_check_percent: 31 },
  { district: "Gondia", expected_check_percent: 66, actual_check_percent: 55 },
  { district: "Hingoli", expected_check_percent: 64, actual_check_percent: 40 },
  { district: "Jalgaon", expected_check_percent: 71, actual_check_percent: 56 },
  { district: "Jalna", expected_check_percent: 66, actual_check_percent: 42 },
  { district: "Kolhapur", expected_check_percent: 80, actual_check_percent: 69 },
  { district: "Latur", expected_check_percent: 69, actual_check_percent: 48 },
  { district: "Mumbai City", expected_check_percent: 88, actual_check_percent: 77 },
  { district: "Mumbai Suburban", expected_check_percent: 85, actual_check_percent: 72 },
  { district: "Nagpur", expected_check_percent: 82, actual_check_percent: 70 },
  { district: "Nanded", expected_check_percent: 68, actual_check_percent: 45 },
  { district: "Nandurbar", expected_check_percent: 62, actual_check_percent: 33 },
  { district: "Nashik", expected_check_percent: 76, actual_check_percent: 62 },
  { district: "Osmanabad", expected_check_percent: 65, actual_check_percent: 41 },
  { district: "Palghar", expected_check_percent: 70, actual_check_percent: 50 },
  { district: "Parbhani", expected_check_percent: 66, actual_check_percent: 44 },
  { district: "Pune", expected_check_percent: 85, actual_check_percent: 74 },
  { district: "Raigad", expected_check_percent: 74, actual_check_percent: 60 },
  { district: "Ratnagiri", expected_check_percent: 72, actual_check_percent: 58 },
  { district: "Sangli", expected_check_percent: 77, actual_check_percent: 64 },
  { district: "Satara", expected_check_percent: 76, actual_check_percent: 63 },
  { district: "Sindhudurg", expected_check_percent: 70, actual_check_percent: 59 },
  { district: "Solapur", expected_check_percent: 74, actual_check_percent: 55 },
  { district: "Thane", expected_check_percent: 83, actual_check_percent: 68 },
  { district: "Wardha", expected_check_percent: 68, actual_check_percent: 57 },
  { district: "Washim", expected_check_percent: 64, actual_check_percent: 46 },
  { district: "Yavatmal", expected_check_percent: 67, actual_check_percent: 48 },
];

export const karnatakaDistrictData = [
  { district: "Bagalkot", expected_check_percent: 72, actual_check_percent: 58 },
  { district: "Ballari", expected_check_percent: 70, actual_check_percent: 55 },
  { district: "Belagavi", expected_check_percent: 75, actual_check_percent: 62 },
  { district: "Bengaluru Rural", expected_check_percent: 80, actual_check_percent: 70 },
  { district: "Bengaluru Urban", expected_check_percent: 88, actual_check_percent: 78 },
  { district: "Bidar", expected_check_percent: 68, actual_check_percent: 50 },
  { district: "Chamarajanagar", expected_check_percent: 65, actual_check_percent: 48 },
  { district: "Chikballapur", expected_check_percent: 70, actual_check_percent: 54 },
  { district: "Chikkamagaluru", expected_check_percent: 74, actual_check_percent: 60 },
  { district: "Chitradurga", expected_check_percent: 69, actual_check_percent: 52 },
  { district: "Dakshina Kannada", expected_check_percent: 85, actual_check_percent: 75 },
  { district: "Davanagere", expected_check_percent: 73, actual_check_percent: 58 },
  { district: "Dharwad", expected_check_percent: 76, actual_check_percent: 64 },
  { district: "Gadag", expected_check_percent: 70, actual_check_percent: 52 },
  { district: "Hassan", expected_check_percent: 74, actual_check_percent: 62 },
  { district: "Haveri", expected_check_percent: 71, actual_check_percent: 56 },
  { district: "Kalaburagi", expected_check_percent: 68, actual_check_percent: 45 },
  { district: "Kodagu", expected_check_percent: 72, actual_check_percent: 60 },
  { district: "Kolar", expected_check_percent: 73, actual_check_percent: 58 },
  { district: "Koppal", expected_check_percent: 67, actual_check_percent: 48 },
  { district: "Mandya", expected_check_percent: 75, actual_check_percent: 63 },
  { district: "Mysuru", expected_check_percent: 82, actual_check_percent: 71 },
  { district: "Raichur", expected_check_percent: 66, actual_check_percent: 44 },
  { district: "Ramanagara", expected_check_percent: 72, actual_check_percent: 58 },
  { district: "Shivamogga", expected_check_percent: 76, actual_check_percent: 64 },
  { district: "Tumakuru", expected_check_percent: 74, actual_check_percent: 60 },
  { district: "Udupi", expected_check_percent: 84, actual_check_percent: 74 },
  { district: "Uttara Kannada", expected_check_percent: 78, actual_check_percent: 66 },
  { district: "Vijayapura", expected_check_percent: 71, actual_check_percent: 54 },
  { district: "Yadgir", expected_check_percent: 64, actual_check_percent: 40 },
];

export const mpDistrictData = [
  { district: "Agar Malwa", expected_check_percent: 62, actual_check_percent: 45 },
  { district: "Alirajpur", expected_check_percent: 58, actual_check_percent: 32 },
  { district: "Anuppur", expected_check_percent: 60, actual_check_percent: 40 },
  { district: "Ashoknagar", expected_check_percent: 64, actual_check_percent: 48 },
  { district: "Balaghat", expected_check_percent: 66, actual_check_percent: 52 },
  { district: "Barwani", expected_check_percent: 60, actual_check_percent: 38 },
  { district: "Betul", expected_check_percent: 65, actual_check_percent: 48 },
  { district: "Bhind", expected_check_percent: 68, actual_check_percent: 50 },
  { district: "Bhopal", expected_check_percent: 82, actual_check_percent: 70 },
  { district: "Burhanpur", expected_check_percent: 63, actual_check_percent: 45 },
  { district: "Chhatarpur", expected_check_percent: 62, actual_check_percent: 42 },
  { district: "Chhindwara", expected_check_percent: 68, actual_check_percent: 54 },
  { district: "Damoh", expected_check_percent: 64, actual_check_percent: 46 },
  { district: "Datia", expected_check_percent: 65, actual_check_percent: 48 },
  { district: "Dewas", expected_check_percent: 70, actual_check_percent: 55 },
  { district: "Dhar", expected_check_percent: 66, actual_check_percent: 48 },
  { district: "Dindori", expected_check_percent: 58, actual_check_percent: 34 },
  { district: "Guna", expected_check_percent: 65, actual_check_percent: 48 },
  { district: "Gwalior", expected_check_percent: 78, actual_check_percent: 64 },
  { district: "Harda", expected_check_percent: 64, actual_check_percent: 48 },
  { district: "Hoshangabad", expected_check_percent: 68, actual_check_percent: 52 },
  { district: "Indore", expected_check_percent: 85, actual_check_percent: 74 },
  { district: "Jabalpur", expected_check_percent: 80, actual_check_percent: 68 },
  { district: "Jhabua", expected_check_percent: 58, actual_check_percent: 32 },
  { district: "Katni", expected_check_percent: 66, actual_check_percent: 50 },
  { district: "Khandwa", expected_check_percent: 65, actual_check_percent: 48 },
  { district: "Khargone", expected_check_percent: 66, actual_check_percent: 50 },
  { district: "Mandla", expected_check_percent: 62, actual_check_percent: 44 },
  { district: "Mandsaur", expected_check_percent: 68, actual_check_percent: 54 },
  { district: "Morena", expected_check_percent: 67, actual_check_percent: 48 },
  { district: "Narsinghpur", expected_check_percent: 66, actual_check_percent: 52 },
  { district: "Neemuch", expected_check_percent: 68, actual_check_percent: 55 },
  { district: "Panna", expected_check_percent: 62, actual_check_percent: 40 },
  { district: "Raisen", expected_check_percent: 66, actual_check_percent: 50 },
  { district: "Rajgarh", expected_check_percent: 64, actual_check_percent: 46 },
  { district: "Ratlam", expected_check_percent: 70, actual_check_percent: 56 },
  { district: "Rewa", expected_check_percent: 68, actual_check_percent: 50 },
  { district: "Sagar", expected_check_percent: 72, actual_check_percent: 58 },
  { district: "Satna", expected_check_percent: 70, actual_check_percent: 54 },
  { district: "Sehore", expected_check_percent: 68, actual_check_percent: 52 },
  { district: "Seoni", expected_check_percent: 65, actual_check_percent: 48 },
  { district: "Shahdol", expected_check_percent: 64, actual_check_percent: 44 },
  { district: "Shajapur", expected_check_percent: 66, actual_check_percent: 50 },
  { district: "Sheopur", expected_check_percent: 62, actual_check_percent: 40 },
  { district: "Shivpuri", expected_check_percent: 65, actual_check_percent: 48 },
  { district: "Sidhi", expected_check_percent: 63, actual_check_percent: 42 },
  { district: "Singrauli", expected_check_percent: 62, actual_check_percent: 40 },
  { district: "Tikamgarh", expected_check_percent: 64, actual_check_percent: 46 },
  { district: "Ujjain", expected_check_percent: 76, actual_check_percent: 62 },
  { district: "Umaria", expected_check_percent: 60, actual_check_percent: 42 },
  { district: "Vidisha", expected_check_percent: 68, actual_check_percent: 52 },
];

