/**
 * Dummy risk data for all Indian states.
 * Used to colour the country-level map.
 * risk: "low" | "medium" | "high"
 */
export const indiaStateData = [
  { state: "Andhra Pradesh",           expected: 72, actual: 58, risk: "medium" },
  { state: "Arunachal Pradesh",        expected: 55, actual: 30, risk: "high"   },
  { state: "Assam",                    expected: 65, actual: 40, risk: "high"   },
  { state: "Bihar",                    expected: 60, actual: 32, risk: "high"   },
  { state: "Chhattisgarh",             expected: 65, actual: 45, risk: "high"   },
  { state: "Goa",                      expected: 82, actual: 75, risk: "low"    },
  { state: "Gujarat",                  expected: 75, actual: 62, risk: "medium" },
  { state: "Haryana",                  expected: 74, actual: 60, risk: "medium" },
  { state: "Himachal Pradesh",         expected: 78, actual: 69, risk: "low"    },
  { state: "Jharkhand",                expected: 62, actual: 38, risk: "high"   },
  { state: "Karnataka",                expected: 76, actual: 63, risk: "medium" },
  { state: "Kerala",                   expected: 88, actual: 80, risk: "low"    },
  { state: "Madhya Pradesh",           expected: 65, actual: 42, risk: "high"   },
  { state: "Maharashtra",              expected: 74, actual: 55, risk: "high"   },
  { state: "Manipur",                  expected: 60, actual: 37, risk: "high"   },
  { state: "Meghalaya",                expected: 58, actual: 34, risk: "high"   },
  { state: "Mizoram",                  expected: 65, actual: 50, risk: "medium" },
  { state: "Nagaland",                 expected: 58, actual: 35, risk: "high"   },
  { state: "Odisha",                   expected: 65, actual: 46, risk: "high"   },
  { state: "Punjab",                   expected: 78, actual: 66, risk: "medium" },
  { state: "Rajasthan",                expected: 68, actual: 46, risk: "high"   },
  { state: "Sikkim",                   expected: 72, actual: 62, risk: "medium" },
  { state: "Tamil Nadu",               expected: 82, actual: 72, risk: "low"    },
  { state: "Telangana",                expected: 75, actual: 61, risk: "medium" },
  { state: "Tripura",                  expected: 65, actual: 49, risk: "medium" },
  { state: "Uttar Pradesh",            expected: 62, actual: 34, risk: "high"   },
  { state: "Uttarakhand",              expected: 72, actual: 58, risk: "medium" },
  { state: "West Bengal",              expected: 70, actual: 55, risk: "medium" },
  { state: "Delhi",                    expected: 85, actual: 72, risk: "medium" },
  { state: "Jammu and Kashmir",        expected: 68, actual: 48, risk: "medium" },
  { state: "Ladakh",                   expected: 60, actual: 42, risk: "high"   },
  { state: "Chandigarh",               expected: 86, actual: 78, risk: "low"    },
  { state: "Puducherry",               expected: 80, actual: 70, risk: "low"    },
  { state: "Andaman and Nicobar",      expected: 72, actual: 62, risk: "medium" },
  { state: "Dadra and Nagar Haveli",   expected: 68, actual: 50, risk: "medium" },
  { state: "Daman and Diu",            expected: 74, actual: 64, risk: "medium" },
  { state: "Lakshadweep",              expected: 70, actual: 60, risk: "medium" },
];
